version: "3.3"
services:
  php-fpm:
    image: webdevops/php-dev:8.2
    hostname: php-fpm
    volumes:
      - "./:/app"
    working_dir: "/app"
    depends_on:
      - mysql
  nginx:
    image: webdevops/nginx
    hostname: nginx
    environment:
      WEB_DOCUMENT_ROOT: "/app/index.php"
      WEB_DOCUMENT_INDEX: "index.php"
      WEB_PHP_SOCKET: php-fpm:9000
    ports:
      - "80:80"
    volumes:
      - "./:/app"
    depends_on:
      - php-fpm
  mysql:
    image: mysql:5.7
    hostname: mysql
    volumes:
      - "./:/app"
    working_dir: "/app"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ipr
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"