version: "3.3"
services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    volumes:
      - "./:/app"
    working_dir: "/app"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ipr
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"